export const CONFIG = {
  viewport: {
    virtualWidth: 1000,
    virtualHeight: 1778,
    backgroundColor: "#0b0b14",
  },
  assets: {
    preload: true,
    skin: "default",
    particles: {
      basePath: "assets/textures/particles/",
      sets: {
        default: [
          "pt_5star03.png",
          "pt_abst00.png",
          "pt_abst08.png",
          "pt_abst11.png",
          "pt_abs_a46.png",
          "pt_photo_b13.png",
          "pt_photo_b18.png",
          "pt_photo_b23.png",
          "pt_photo_b24.png",
          "pt_skull_n02.png",
          "pt_star_a06.png",
          "pt_star_a11.png",
          "pt_star_a13.png",
        ],
      },
    },
  },
  configFiles: {
    defaultPath: "configs/default.json",
    available: ["configs/default.json", "configs/retro.json"],
    storageKey: "selectedConfigPath",
  },
  input: {
    horizontalFollow: 0.45,
    maxPointerDelta: 320,
  },
  physics: {
    gravity: 2200,
    jumpVelocity: 1300,
    moveSpeed: 1200,
    maxFallSpeed: 3600,
  },
  player: {
    radius: 32,
    color: "#ffe66d",
  },
  ground: {
    height: 90,
    color: "#1b1b2a",
  },
  camera: {
    targetScreenY: 0.62,
    smooth: 0.1,
  },
  platforms: {
    width: 100,
    height: 24,
    horizontalRange: 0.42,
    minGap: 140,
    maxGap: 200,
    startCount: 8,
    destroyOnJump: true,
    respawnOnGround: true,
    fadeDuration: 0.2,
    descentSpeed: 0,
    colors: ["#8fe388", "#87d8ff", "#f6a4ff", "#ffd580"],
    rareColor: "#ffffff",
    rareChance: 0.08,
  },
  particles: {
    poolSize: 9000,
    tail: {
      snapToGrid: true,
      gridSize: 3,
      growthPerJump: 0.08,
      globalAlpha: 1,
      globalSpawnMul: 1,
      globalLifeMul: 1,
      globalSizeMul: 1,
      progressStages: [
        { min: 0.0, max: 0.15, spawnMul: 0.4, lifeMul: 0.7, sizeMul: 0.8 },
        { min: 0.15, max: 0.3, spawnMul: 0.6, lifeMul: 0.85, sizeMul: 0.9 },
        { min: 0.3, max: 0.5, spawnMul: 0.8, lifeMul: 1.0, sizeMul: 1.0 },
        { min: 0.5, max: 0.7, spawnMul: 1.0, lifeMul: 1.1, sizeMul: 1.05 },
        { min: 0.7, max: 0.9, spawnMul: 1.25, lifeMul: 1.25, sizeMul: 1.15 },
        { min: 0.9, max: 1.0, spawnMul: 1.5, lifeMul: 1.4, sizeMul: 1.25 },
      ],
      viewer: {
        enabled: true,
        storageKey: "tailViewerConfig",
        defaultLayerIndex: 0,
      },
      layers: [
        {
          name: "Core",
          enabled: true,
          enabledAt: 0,
          mode: "follow",
          shape: "circle",
          texture: null,
          colorMode: "fixed",
          colorFrom: "#CFE9FF",
          colorTo: "#CFE9FF",
          baseSpawnRate: 120,
          maxSpawnRate: 260,
          life: { min: 0.25, max: 0.65 },
          scaleFrom: { min: 1.65, max: 2.35 },
          scaleTo: { min: 1.65, max: 2.35 },
          alphaFrom: { min: 0.85, max: 0.85 },
          alphaTo: { min: 0.85, max: 0.85 },
          rotationFrom: { min: 0, max: 0 },
          rotationTo: { min: 0, max: 0 },
          angularSpeed: { min: 0, max: 0 },
          speed: {
            vx: { min: 0, max: 0 },
            vy: { min: 0, max: 0 },
          },
          followStrength: 1,
          offsetRadius: 0,
          offsetBias: 0,
          gravity: { x: 0, y: 0 },
          airDrag: 0,
        },
        {
          name: "Inner",
          enabled: true,
          enabledAt: 0.1,
          mode: "follow",
          shape: "square",
          texture: null,
          colorMode: "platform",
          baseSpawnRate: 90,
          maxSpawnRate: 220,
          life: { min: 0.3, max: 0.8 },
          scaleFrom: { min: 2.4, max: 3.6 },
          scaleTo: { min: 2.4, max: 3.6 },
          alphaFrom: { min: 0.55, max: 0.55 },
          alphaTo: { min: 0.55, max: 0.55 },
          rotationFrom: { min: 0, max: 0 },
          rotationTo: { min: 0, max: 0 },
          angularSpeed: { min: 0, max: 0 },
          speed: {
            vx: { min: -10.5, max: 10.5 },
            vy: { min: -10.5, max: 10.5 },
          },
          followStrength: 0.95,
          offsetRadius: 0.8,
          offsetBias: 0,
          gravity: { x: 0, y: 0 },
          airDrag: 0,
        },
        {
          name: "Outer",
          enabled: true,
          enabledAt: 0.35,
          mode: "follow",
          shape: "circle",
          texture: null,
          colorMode: "palette",
          palette: ["#FF3B30", "#FFB020", "#FFE66D"],
          paletteBlend: 0.65,
          baseSpawnRate: 55,
          maxSpawnRate: 140,
          life: { min: 0.35, max: 1.05 },
          scaleFrom: { min: 3.8, max: 6.2 },
          scaleTo: { min: 3.8, max: 6.2 },
          alphaFrom: { min: 0.22, max: 0.22 },
          alphaTo: { min: 0.22, max: 0.22 },
          rotationFrom: { min: 0, max: 0 },
          rotationTo: { min: 0, max: 0 },
          angularSpeed: { min: 0, max: 0 },
          speed: {
            vx: { min: -18.8, max: 18.8 },
            vy: { min: -18.8, max: 18.8 },
          },
          followStrength: 0.9,
          offsetRadius: 1.6,
          offsetBias: 0,
          gravity: { x: 0, y: 0 },
          airDrag: 0,
        },
        {
          name: "Aura",
          enabled: true,
          enabledAt: 0.6,
          mode: "aura",
          shape: "circle",
          texture: null,
          colorMode: "palette",
          palette: ["#5AF7FF", "#7C4DFF", "#FF4FD8"],
          paletteBlend: 0.45,
          baseSpawnRate: 35,
          maxSpawnRate: 90,
          life: { min: 0.4, max: 1.2 },
          scaleFrom: { min: 3, max: 5 },
          scaleTo: { min: 3, max: 5 },
          alphaFrom: { min: 0.18, max: 0.18 },
          alphaTo: { min: 0.18, max: 0.18 },
          rotationFrom: { min: 0, max: 0 },
          rotationTo: { min: 0, max: 0 },
          angularSpeed: { min: 0, max: 0 },
          speed: {
            vx: { min: -23, max: 23 },
            vy: { min: -23, max: 23 },
          },
          followStrength: 0,
          offsetRadius: 10,
          offsetBias: 0,
          gravity: { x: 0, y: -12 },
          airDrag: 0.15,
        },
        {
          name: "Sparks",
          enabled: true,
          enabledAt: 0.75,
          mode: "spark",
          shape: "square",
          texture: null,
          colorMode: "fixed",
          colorFrom: "#ffffff",
          colorTo: "#ffffff",
          baseSpawnRate: 6,
          maxSpawnRate: 22,
          life: { min: 0.1, max: 0.6 },
          scaleFrom: { min: 2, max: 4 },
          scaleTo: { min: 2, max: 4 },
          alphaFrom: { min: 0.75, max: 0.75 },
          alphaTo: { min: 0.75, max: 0.75 },
          rotationFrom: { min: 0, max: 0 },
          rotationTo: { min: 0, max: 0 },
          angularSpeed: { min: 0, max: 0 },
          speed: {
            vx: { min: -81.2, max: 81.2 },
            vy: { min: -81.2, max: 81.2 },
          },
          followStrength: 0,
          offsetRadius: 2,
          offsetBias: 0,
          gravity: { x: 0, y: 35 },
          airDrag: 0,
        },
      ],
    },
    platform: {
      burstCount: 370,
      speed: {
        vx: { min: -420, max: 420 },
        vy: { min: -420, max: 420 },
      },
      life: { min: 0.285, max: 1.285 },
      scaleFrom: { min: 1, max: 5 },
      scaleTo: { min: 1, max: 5 },
      alphaFrom: { min: 0.65, max: 0.65 },
      alphaTo: { min: 0.65, max: 0.65 },
      rotationFrom: { min: 0, max: 0 },
      rotationTo: { min: 0, max: 0 },
      angularSpeed: { min: 0, max: 0 },
      gravity: { x: 0, y: 90 },
      airDrag: 0,
      colorFrom: null,
      colorTo: null,
      texture: null,
      shape: "square",
    },
  },
  pixelOverlay: {
    enabled: false,
    gridSize: 2,
    pattern: "_0\n0_",
    presets: {
      "Checkers": "_0\n0_",
      "Pixel Screen": "_0_0\n____",
      "Scanlines": "0\n_",
      "Cross": "__0___\n_0_0__\n__0___\n_______",
    },
  },
  parallax: {
    layers: [
      { speed: 0.15, color: "#151527", dotColor: "#22223d", dotCount: 30 },
      { speed: 0.3, color: "#10101f", dotColor: "#2a2a4a", dotCount: 40 },
      { speed: 0.5, color: "#0b0b14", dotColor: "#34345c", dotCount: 50 },
    ],
  },
  difficulty: {
    mode: "soft",
    rescuePlatformChance: 0,
    rescueCooldown: 1.5,
  },
  audio: {
    enabled: true,
    volume: 0.45,
    background: ["assets/audio/background_1.mp3"],
    jump: ["assets/audio/jump_1.mp3"],
    platform: ["assets/audio/platform_1.mp3"],
    fall: ["assets/audio/fall_1.mp3"],
  },
};
