export const CONFIG = {
  viewport: {
    virtualWidth: 1000,
    virtualHeight: 1778,
    backgroundColor: "#0b0b14",
  },
  input: {
    horizontalFollow: 0.45,
    maxPointerDelta: 320,
  },
  physics: {
    gravity: 2200,
    jumpVelocity: 1300,
    moveSpeed: 1200,
    maxFallSpeed: 3600,
  },
  player: {
    radius: 32,
    color: "#ffe66d",
  },
  ground: {
    height: 90,
    color: "#1b1b2a",
  },
  camera: {
    targetScreenY: 0.62,
    smooth: 0.1,
  },
  platforms: {
    width: 100,
    height: 24,
    horizontalRange: 0.42,
    minGap: 140,
    maxGap: 200,
    startCount: 8,
    destroyOnJump: true,
    respawnOnGround: true,
    fadeDuration: 0.2,
    descentSpeed: 0,
    colors: ["#8fe388", "#87d8ff", "#f6a4ff", "#ffd580"],
    rareColor: "#ffffff",
    rareChance: 0.08,
  },
  particles: {
    poolSize: 9000,
    tail: {
      snapToGrid: true,
      gridSize: 3,
      growthPerJump: 0.08,
      globalAlpha: 1,
      globalSpawnMul: 1,
      globalLifeMul: 1,
      globalSizeMul: 1,
      progressStages: [
        { min: 0.0, max: 0.15, spawnMul: 0.4, lifeMul: 0.7, sizeMul: 0.8 },
        { min: 0.15, max: 0.3, spawnMul: 0.6, lifeMul: 0.85, sizeMul: 0.9 },
        { min: 0.3, max: 0.5, spawnMul: 0.8, lifeMul: 1.0, sizeMul: 1.0 },
        { min: 0.5, max: 0.7, spawnMul: 1.0, lifeMul: 1.1, sizeMul: 1.05 },
        { min: 0.7, max: 0.9, spawnMul: 1.25, lifeMul: 1.25, sizeMul: 1.15 },
        { min: 0.9, max: 1.0, spawnMul: 1.5, lifeMul: 1.4, sizeMul: 1.25 },
      ],
      viewer: {
        enabled: true,
        storageKey: "tailViewerConfig",
        defaultLayerIndex: 0,
      },
      layers: [
        {
          name: "Core",
          enabled: true,
          enabledAt: 0,
          mode: "follow",
          shape: "circle",
          colorMode: "fixed",
          color: "#CFE9FF",
          baseSpawnRate: 120,
          maxSpawnRate: 260,
          life: 0.45,
          lifeJitter: 0.2,
          size: 2,
          sizeJitter: 0.35,
          alpha: 0.85,
          followStrength: 1,
          offsetRadius: 0,
          offsetBias: 0,
          driftSpeed: 0,
          driftJitter: 0,
          gravity: 0,
          airPush: 0,
        },
        {
          name: "Inner",
          enabled: true,
          enabledAt: 0.1,
          mode: "follow",
          shape: "square",
          colorMode: "platform",
          baseSpawnRate: 90,
          maxSpawnRate: 220,
          life: 0.55,
          lifeJitter: 0.25,
          size: 3,
          sizeJitter: 0.6,
          alpha: 0.55,
          followStrength: 0.95,
          offsetRadius: 0.8,
          offsetBias: 0,
          driftSpeed: 10,
          driftJitter: 0.5,
          gravity: 0,
          airPush: 0,
        },
        {
          name: "Outer",
          enabled: true,
          enabledAt: 0.35,
          mode: "follow",
          shape: "circle",
          colorMode: "palette",
          palette: ["#FF3B30", "#FFB020", "#FFE66D"],
          paletteBlend: 0.65,
          baseSpawnRate: 55,
          maxSpawnRate: 140,
          life: 0.7,
          lifeJitter: 0.35,
          size: 5,
          sizeJitter: 1.2,
          alpha: 0.22,
          followStrength: 0.9,
          offsetRadius: 1.6,
          offsetBias: 0,
          driftSpeed: 18,
          driftJitter: 0.8,
          gravity: 0,
          airPush: 0,
        },
        {
          name: "Aura",
          enabled: true,
          enabledAt: 0.6,
          mode: "aura",
          shape: "circle",
          colorMode: "palette",
          palette: ["#5AF7FF", "#7C4DFF", "#FF4FD8"],
          paletteBlend: 0.45,
          baseSpawnRate: 35,
          maxSpawnRate: 90,
          life: 0.8,
          lifeJitter: 0.4,
          size: 4,
          sizeJitter: 1,
          alpha: 0.18,
          followStrength: 0,
          offsetRadius: 10,
          offsetBias: 0,
          driftSpeed: 22,
          driftJitter: 1,
          gravity: -12,
          airPush: 0.15,
        },
        {
          name: "Sparks",
          enabled: true,
          enabledAt: 0.75,
          mode: "spark",
          shape: "square",
          colorMode: "fixed",
          color: "#ffffff",
          baseSpawnRate: 6,
          maxSpawnRate: 22,
          life: 0.35,
          lifeJitter: 0.25,
          size: 3,
          sizeJitter: 1,
          alpha: 0.75,
          followStrength: 0,
          offsetRadius: 2,
          offsetBias: 0,
          driftSpeed: 80,
          driftJitter: 1.2,
          gravity: 35,
          airPush: 0,
        },
      ],
    },
    platform: {
      burstCount: 370,
      minSpeed: -420,
      maxSpeed: 420,
      life: 0.785,
      lifeJitter: 0.5,
      size: 3,
      sizeJitter: 2,
      gravity: 90,
      airPush: 0,
      spread: Math.PI * 2,
      alpha: 0.65,
      shape: "square",
    },
  },
  parallax: {
    layers: [
      { speed: 0.15, color: "#151527", dotColor: "#22223d", dotCount: 30 },
      { speed: 0.3, color: "#10101f", dotColor: "#2a2a4a", dotCount: 40 },
      { speed: 0.5, color: "#0b0b14", dotColor: "#34345c", dotCount: 50 },
    ],
  },
  difficulty: {
    mode: "soft",
    rescuePlatformChance: 0,
    rescueCooldown: 1.5,
  },
  audio: {
    enabled: true,
    volume: 0.45,
    background: ["assets/audio/background_1.mp3"],
    jump: ["assets/audio/jump_1.mp3"],
    platform: ["assets/audio/platform_1.mp3"],
    fall: ["assets/audio/fall_1.mp3"],
  },
};
